import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import React, {
  useState,
  useTransition,
  useRef,
  useEffect,
  HtmlHTMLAttributes,
} from "react";
import {
  ClerkProvider,
  RedirectToOrganizationProfile,
  RedirectToSignIn,
  useUser,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";
import { userAgent } from "next/server";
import { userInfo } from "os";
import { boolean, record } from "zod";
import type {
  User,
  Workout,
  WorkoutPlan,
  ActualWorkout,
  ActualExercise,
  exerciseSet,
  WorkoutPlanTwo,
} from "@prisma/client";
import { prisma } from "~/server/db";
import { empty } from "@prisma/client/runtime";
import { SourceTextModule } from "vm";
import { v4 } from "uuid";
import { existsSync } from "fs";
import { create } from "domain";
import { useRouter } from "next/router";
import { describe } from "node:test";
import { TEMPORARY_REDIRECT_STATUS } from "next/dist/shared/lib/constants";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Lyfter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b   from-[#000000]  to-[#44454b]  text-white">
        <nav className="flex items-center justify-between">
          <SignedIn>
            <div className="m-2 flex flex-col text-white ">
              <UserButton
                appearance={{
                  elements: { userButtonAvatarBox: { width: 45, height: 45 } },
                }}
              />
            </div>
          </SignedIn>
          <div className="flex space-x-6 pr-4">
            <Link
              href="home"
              className="text-gray-300 hover:text-white hover:underline"
            >
              Home
            </Link>
            <Link
              href="makeplan"
              className="text-gray-300 hover:text-white hover:underline"
            >
              Edit Plan
            </Link>
            <Link
              href="allworkouts"
              className="text-gray-300 hover:text-white hover:underline"
            >
              History
            </Link>
          </div>
        </nav>
        <div>
          <SignedIn>
            <br></br>
            <Content />
            <br></br>
            <div></div>
          </SignedIn>
          <SignedOut>
            {/* Signed out users get sign in button */}
            <SignInButton redirectUrl="home">
              <button className="rounded-full bg-white p-3 text-xl text-black">
                Sign In
              </button>
            </SignInButton>
          </SignedOut>
        </div>
      </main>
    </>
  );
};

export default Home;

function Content(){
    const user = useUser()
    
    return (
        <div>
            <Workouts/>
        </div>
    )
}

function Workouts() { 
    const { data: workoutPlans, isLoading: workoutsLoading } = api.getWorkouts.getPlanByUserId.useQuery()

    const [selectedPlan, setSelectedPlan ] = useState<WorkoutPlanTwo & {
    workouts: (ActualWorkout & {
        exercises: (ActualExercise & {
            sets: exerciseSet[];
        })[];
    })[];
}>()

    if (workoutsLoading) {
        return (
            <div>
              <div
              className="inline-block h-8 w-8 animate-spin rounded-full border-4 border-solid border-current border-r-transparent align-[-0.125em] text-primary motion-reduce:animate-[spin_1.5s_linear_infinite]"
              role="status">
              <span
                className="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]"
                >Loading...</span
              >
            </div>
            </div>
        )}


    if (!workoutPlans || workoutPlans === undefined){
        return(<div>No Workout History</div>)
    }

    const handleButtonClick = (plan: WorkoutPlanTwo & {
    workouts: (ActualWorkout & {
        exercises: (ActualExercise & {
            sets: exerciseSet[];
        })[];
    })[];
}) => {
      setSelectedPlan(plan)
    }

    return (
        <div className="flex flex-wrap">
          <DisplayPlan plan={selectedPlan}/>
              <div>
      {workoutPlans.map((plan) => (
        <div key={plan.planId}>
          <h2>{plan.date.toLocaleDateString()} Plan
          {" "}<button
          onClick={() => handleButtonClick(plan)}
          >Select</button>
          </h2>
        </div>
      ))}
    </div>
        </div>
    )
}

interface DisplayPlanProps {
  plan: WorkoutPlanTwo & {
    workouts: (ActualWorkout & {
        exercises: (ActualExercise & {
            sets: exerciseSet[];
        })[];
    })[];
} | undefined;
}

function DisplayPlan({plan}: DisplayPlanProps){
  if (!plan){
    return(
      <div></div>
    )
  }
  return(
    <div>
      {plan.workouts.map((workout) => (
            <div key={workout.workoutId}>
              <h4>{workout.nominalDay}</h4>
              <p>{workout.description}</p>
              {workout.exercises.map((exercise) => (
                <div key={exercise.exerciseId}>
                  <p>{exercise.description}</p>
                  {exercise.sets.map((set) => (
                    <div key={set.setId}>
                      <p>Weight: {set.weight}, Reps: {set.reps}, RIR: {set.rir}</p>
                    </div>
                  ))}
                </div>
              ))}
              </div>))}
    </div>
  )
}

interface ExerciseDisplayProps {
  workoutId: string
}

function ExerciseDisplay( {workoutId} : ExerciseDisplayProps){
    const {data: exercises, isLoading: exercisesLoading} = api.getWorkouts.getExerciseByWorkoutId.useQuery({
      workoutId: workoutId
    })
    console.log("exercises:")
    console.log(exercises)
    if (exercisesLoading){
      return(
              <div
              className="inline-block h-8 w-8 animate-spin rounded-full border-4 border-solid border-current border-r-transparent align-[-0.125em] text-primary motion-reduce:animate-[spin_1.5s_linear_infinite]"
              role="status">
              <span
                className="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]"
                >Loading...</span
              >
            </div>
      )
    }
      if (exercises) {
    return (
      <div>
      <table className="mx-auto">
          <thead>
            <tr>
              <th>Exercise</th>
              <th>Weight</th>
              <th>Sets</th>
            </tr>
          </thead>
          <tbody>
            { exercises && exercises.map((exercise, index) =>(
              <tr key={index}>
                <td>{exercise.description}</td>
                <td>{exercise.weight}</td>
                <td>{exercise.sets}</td>
              </tr>
            )) }
          </tbody>
        </table>
      </div>
    );
  }
  return <div>No data</div>;
}
  
