import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import React, { useState, useTransition } from 'react'
import {
  ClerkProvider,
  RedirectToOrganizationProfile,
  RedirectToSignIn,
  useUser,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton
} from "@clerk/nextjs";
import { userAgent } from "next/server";
import { userInfo } from "os";
import { boolean } from "zod";
import type { User, Workout, WorkoutPlan } from "@prisma/client"
import { prisma } from "~/server/db";

//@refresh reset





const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Lyfter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-white text-center flex min-h-screen   flex-col  bg-gradient-to-b from-[#000000] to-[#44454b]">
<nav className="flex items-center justify-between flex-wrap bg-black-500 p-6">
        <SignedIn>

            <div className="text-white   items-end flex p-6 items-right flex-col ">
                <UserButton appearance={{ 
                  elements: { 
                    userButtonAvatarBox: { width: 60, height: 60 } 
                    }
                  }} />
            </div>
        </SignedIn>
  <div className="flex items-center flex-shrink-0 text-white mr-6">
  </div>
  <div className="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div className="text-sm lg:flex-grow">
      <Link href="home" className="block mt-4 lg:inline-block lg:mt-0 text-slate-200 hover:text-white mr-4">Home</Link>
      <Link href="makeplan" className="block mt-4 lg:inline-block lg:mt-0 text-slate-200 hover:text-white mr-4">Edit Workout Plan</Link>
      < Link href="allworkouts" className="block mt-4 lg:inline-block lg:mt-0 text-slate-200 hover:text-white mr-4">Workout History</Link>
    </div>
    <div>
    </div>
  </div>
</nav>
        <div>
          <SignedIn>
          <br></br>
          <NewWorkoutUi />
          <br></br>
      <div>
      </div>
        </SignedIn>
        <SignedOut>
          {/* Signed out users get sign in button */}
          <SignInButton redirectUrl="home">
            <button className="rounded-full text-xl text-black bg-white p-3">Sign In</button>
            </SignInButton>
        </SignedOut>
      </div>
      </main>
    </>
  );
};

export default Home;

function NewWorkoutUi(){
  return(
    <div>
      <MakePplSplit></MakePplSplit>
      <br></br>
      <WeekForm></WeekForm>
    </div>
  )
}

function WeekForm(){
  const [daysSelected, setDaysSelected] = useState<string[]>([])
  const daysOfWeek : string[]= ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  
  function handleCheck(newDay: string, checked: boolean){
    if (checked) {
      setDaysSelected(prevDays => [...prevDays, newDay]);
    } else {
      setDaysSelected(prevDays => prevDays.filter(day => day !== newDay));
    }
  }

  return(
    <div>
      <div className="text-3xl font-bold text-slate-300 text-center mb-4">Select Workout Days</div>
      <div className="flex flex-col items-center">
        <div className="flex flex-row items-center">
          {daysOfWeek.map((day) => (
            <div key={day} className="flex flex-col items-center">
              <span className="ml-2 text-lg">{day}</span>
              <input type="checkbox" onChange={(event)=>handleCheck(day, event.target.checked)} className="form-checkbox h-6 w-6"/>
            </div>
          ))}
        </div>
      </div>
      <WorkoutForm days={daysSelected}/>
    </div>
  )
}

interface WorkoutFormProps {
  days: string[]
}

interface WorkoutPlanInput {
  sunday: string;
  monday: string;
  tuesday: string;
  wednesday: string;
  thursday: string;
  friday: string;
  saturday: string;
}


function WorkoutForm( {days} : WorkoutFormProps){

  if (days.length === 0){ return <div></div>}

  const sortedDays = [...days].sort((a, b) => {
    const order = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
    return order.indexOf(a) - order.indexOf(b);
  });

  const newPlan : WorkoutPlanInput = {
    sunday: "",
    monday: "",
    tuesday: "",
    wednesday: "",
    thursday: "",
    friday: "",
    saturday: "",
  }

  const {mutate: makePlan, isLoading} = api.getWorkouts.newWorkoutPlan.useMutation({
    onSuccess(data, variables, context) {
      console.log(data)
    },
    })

  function handleSubmit(event: React.FormEvent<HTMLFormElement>){
    event?.preventDefault()
    const formData = new FormData(event.currentTarget)
    const input = Object.fromEntries(formData.entries())
    Object.keys(input).forEach((day) => {
      if (input[day] !== undefined){
        newPlan[day.toLowerCase() as keyof WorkoutPlanInput] = input[day] as string
      }
    })
    console.log(newPlan)
    makePlan(newPlan)
  }
  return(
    <div>
    <div className="container mx-auto px-4 py-8">
        <h1 className="text-2xl font-bold mb-4">Create Your Weekly Workout Plan</h1>
        <form  onSubmit={handleSubmit}>
          {sortedDays.map((day) => (
            <div className="flex flex-wrap mb-4" key={day}>
              <label htmlFor={day} className="w-full sm:w-1/4">{day}:</label>
              <div className="w-full sm:w-3/4">
                <input type="text" id={day} name={day} className="w-full px-3 py-2 border text-black border-gray-400 rounded"></input>
              </div>
            </div>
          ))}
          <div className="mt-8">
            <button type="submit" className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Submit</button>
          </div>
        </form>
    </div>
    </div>
  )
}

function MakePplSplit(){
  const {mutate: makePlan, isLoading} = api.getWorkouts.newWorkoutPlan.useMutation({
    onSuccess(data, variables, context) {
      console.log(data)
    },
    })

  const user = useUser()
  function handleClick(){
    console.log('clicked')
    
  }
  return(<div>
    <button
     onClick={handleClick}
     className="p-5 hover:underline hover:bg-slate-300 rounded-full bg-slate-400">Use the best Push/Pull/Legs Split ever</button>
  </div>)
}

type ExerciseTemplate = {
  name: string;
  weight: number;
  sets: number;
};

type WorkoutTemplate = {
  name: string;
  exercises: ExerciseTemplate[];
}

const PushFirst: WorkoutTemplate = {
  name: "Push #1",
  exercises: [
    {name: "Atlantis Side Raise", weight: 90, sets: 4},
    {name: "Calf Raise", weight: 220, sets: 4},
    {name: "Machine Press", weight: 185, sets: 3},
    {name: "Incline DB Press", weight: 60, sets: 2},
    {name: "Cable Pushdown", weight: 120, sets: 4},

  ]
}
const PushSecond: WorkoutTemplate = {
  name: "Push #2",
  exercises: [
    {name: "Machine Press", weight: 185, sets: 3},
    {name: "Incline DB Press", weight: 60, sets: 2},
    {name: "Cable Upright Row", weight: 70, sets: 4},
    {name: "Cable Pushdown", weight: 120, sets: 4},
    {name: "Leg Raise", weight: 0, sets: 4},
  ]
}
const LegFirst: WorkoutTemplate = {
  name: "Legs #1",
  exercises: [
    {name: "DB RDL", weight: 100, sets: 2},
    {name: "Belt Squat", weight: 135, sets: 4},
    {name: "Candlesticks", weight: 0, sets: 4},
  ]
}
const LegSecond: WorkoutTemplate = {
  name: "Legs #2",
  exercises: [
    {name: "Belt Squat", weight: 135, sets: 4},
    {name: "Ham Curl", weight: 100, sets: 4},
    {name: "Calf Raise", weight: 220, sets: 4},
  ]
}
const PullFirst: WorkoutTemplate = {
  name: "Pull #1",
  exercises: [
    {name: "Calf Raise", weight: 220, sets: 4},
    {name: "Lat Pulldown", weight: 140, sets: 4},
    {name: "Machine Row", weight: 185, sets: 4},
    {name: "Bicep Curl", weight: 40, sets: 4},
  ]
}
const PullSecond: WorkoutTemplate = {
  name: "Pull #2",
  exercises: [
    {name: "Machine Row", weight: 185, sets: 4},
    {name: "Lat Pulldown", weight: 140, sets: 4},
    {name: "Atlantis Side Raise", weight: 90, sets: 4},
    {name: "Bicep Curl", weight: 40, sets: 4},
    {name: "Candlesticks", weight: 0, sets: 4},
  ]
}