import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import React, { useState, useTransition } from 'react'
import {
  ClerkProvider,
  RedirectToOrganizationProfile,
  RedirectToSignIn,
  useUser,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton
} from "@clerk/nextjs";
import { userAgent } from "next/server";
import { userInfo } from "os";
import { boolean } from "zod";
import type { User, Workout } from "@prisma/client"
import { prisma } from "~/server/db";
import { start } from "repl";


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Lyfter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-white text-center flex min-h-screen   flex-col  bg-gradient-to-b from-[#000000] to-[#44454b]">
        <div>
          <SignedIn>
            <div className="text-white   items-end flex p-6 items-right flex-col ">
                <UserButton appearance={{ 
                  elements: { 
                    userButtonAvatarBox: { width: 60, height: 60 } 
                    }
                  }} />
            </div>
          <br></br>
          <WorkoutUi />
          <br></br>
      <div>
      </div>
        </SignedIn>
        <SignedOut>
          {/* Signed out users get sign in button */}
          <SignInButton redirectUrl="home">
            <button className="rounded-full text-xl text-black bg-white p-3">Sign In</button>
            </SignInButton>
        </SignedOut>
      </div>
      </main>
    </>
  );
};

export default Home



function WorkoutUi(){
    const [newWorkout, setNewWorkout] = useState<Workout>()

    const {mutate: makeNewWorkout} = api.getWorkouts.newWorkout.useMutation({
    onSuccess(data, variables, context) {
      setNewWorkout(data)
    },
    })
    if (newWorkout){
      console.log(newWorkout)
    }
    function handleWorkoutClick(){
        makeNewWorkout()
    }

    if (!newWorkout){
        return (
            <div>
            {(!newWorkout) && <NewWorkout startWorkout={handleWorkoutClick}/>}
            </div>
    )}
    
    return(
    <WorkoutTable workout={newWorkout}/>
    )

}

interface BeginWorkoutProps {
  startWorkout: React.Dispatch<React.SetStateAction<boolean>>;
}

function NewWorkout({ startWorkout}: BeginWorkoutProps): JSX.Element | null {
    function handleClick(){
        startWorkout(true)
    }
    return(
      <div className="object-contain m-2">
      <button onClick={handleClick} className="p-5 hover:underline hover:bg-slate-300 rounded-full bg-slate-400">New Workout</button>
      </div>
    )
}

interface WorkoutTableProps {
  workout: Workout;
}

function WorkoutTable( {workout}: WorkoutTableProps){
    return(
      <div>
        <div>{workout.description}: {workout.nominalDay}</div>
      </div>
    )

}